services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: timecraft-frontend
    ports:
      - "3000:80"  # serve React app from Nginx
    restart: unless-stopped
