"""Defining relationship between users, tasks and logs so that tasks can be deleted when user is deleted and so on

Revision ID: 543703d68501
Revises: cb2cfa1f74a0
Create Date: 2024-11-05 20:26:58.495474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '543703d68501'
down_revision: Union[str, None] = 'cb2cfa1f74a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
