"""Add unique_id to basemodel

Revision ID: 958ccda321d9
Revises: 
Create Date: 2024-11-05 14:08:48.977451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '958ccda321d9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_log', sa.Column('unique_id', sa.String(length=8), nullable=True))
    op.create_unique_constraint(None, 'daily_log', ['unique_id'])
    op.add_column('tasks', sa.Column('unique_id', sa.String(length=8), nullable=True))
    op.create_unique_constraint(None, 'tasks', ['unique_id'])
    op.add_column('users', sa.Column('unique_id', sa.String(length=8), nullable=True))
    op.create_unique_constraint(None, 'users', ['unique_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'unique_id')
    op.drop_constraint(None, 'tasks', type_='unique')
    op.drop_column('tasks', 'unique_id')
    op.drop_constraint(None, 'daily_log', type_='unique')
    op.drop_column('daily_log', 'unique_id')
    # ### end Alembic commands ###
