"""Changing relationship between tasks and logs to be by unique_id instead of id

Revision ID: cb2cfa1f74a0
Revises: 96f48dd56dbf
Create Date: 2024-11-05 15:18:07.164549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb2cfa1f74a0'
down_revision: Union[str, None] = '96f48dd56dbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('daily_log_task_id_fkey', 'daily_log', type_='foreignkey')
    op.create_foreign_key(None, 'daily_log', 'tasks', ['task_id'], ['unique_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'daily_log', type_='foreignkey')
    op.create_foreign_key('daily_log_task_id_fkey', 'daily_log', 'tasks', ['task_id'], ['id'])
    # ### end Alembic commands ###
