version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: timecraft-api
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - HBNB_API_HOST=0.0.0.0
      - HBNB_API_PORT=5001
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app/v2
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - timecraft-network
    ports:
      - 5000:5000

  postgres:
    image: postgres:16
    container_name: timecraft_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/postgres/init:/docker-entrypoint-initdb.d  # adjust path if needed
    networks:
      - timecraft-network

volumes:
  pgdata:

networks:
  timecraft-network:
    driver: bridge
