version: '3.8'

services:
  api:
    build:
      context: ..
      dockerfile: v2/Dockerfile
    container_name: timecraft-api
    ports:
      - 5001:5001
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - HBNB_API_HOST=0.0.0.0
      - HBNB_API_PORT=5001
      - PYTHONPATH=/backend
      - PYTHONUNBUFFERED=1
    volumes:
      - ..:/backend
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  timecraft-network:
    driver: bridge 